##  Employee Salary Analysis Using Python Pandas

In [1]:
import pandas as pd 

data = pd.read_csv("Salaries.csv")

C:\Users\KaziKudratAli\AppData\Local\Temp\ipykernel_21828\479096339.py:3: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Salaries.csv")

## 1. Display Top 10 Row of Dataset(Salaries.scv)

In [2]:
data.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

## 2. Check Last 10 Row of salaries

In [3]:
data.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

## 3. Find Shape of our dataset(Row and column)

In [4]:
data.shape

(148654, 13)

## 4. Getting information about our dataset

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

## 5. Check Null values in our dataset

In [6]:
data.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

## 6. Drop ID,NOTES,AGENCY AND STATUS COLUMN

In [7]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [8]:
data = data.drop(['Id','Notes','Agency','Status'],axis = 1)

In [9]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

## 7. Get Overall about Statistics about dataset

In [10]:
data.describe(include='all')

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148049.0,148654.0,148654.0,112495.0,148654.000000,148654.000000,148654.000000
unique,110811,2159,109900.0,66555.0,84968.0,99635.0,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,0.0,0.0,0.0,0.0,NaN,NaN,NaN
freq,13,7036,875.0,66103.0,35218.0,1053.0,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,74768.321972,93692.554811,2012.522643
std,NaN,NaN,NaN,NaN,NaN,NaN,50517.005274,62793.533483,1.117538
min,NaN,NaN,NaN,NaN,NaN,NaN,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,105839.135000,132876.450000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,567595.430000,567595.430000,2014.000000

## 8. Find Occurrence of The Employees Names (Top 5)

In [11]:
data['EmployeeName'].value_counts().head()

EmployeeName
Kevin Lee       13
William Wong    11
Richard Lee     11
Steven Lee      11
John Chan        9
Name: count, dtype: int64

## 9. Find Unique Number of Job Title

In [12]:
data['JobTitle'].nunique()

2159

## 10. Find Total Number OF Job Title contain Captain

In [13]:
data['JobTitle'].str.contains('Captain',case=False).sum()

np.int64(552)

## 11. Display all The Names From Fire Department

In [14]:
data[data['JobTitle'].str.contains('Fair',case=False)][['EmployeeName','JobTitle','BasePay','OvertimePay','TotalPay']]

,EmployeeName,JobTitle,BasePay,OvertimePay,TotalPay
7520,JENNIFER KASS,GOVERNMENT AND PUBLIC AFFAIRS MANAGER,110219.06,0.0,110219.06
7521,SHARYN SASLAFSKY,GOVERNMENT AND PUBLIC AFFAIRS MANAGER,110219.0,0.0,110219.00
7522,BART BROOME,GOVERNMENT AND PUBLIC AFFAIRS MANAGER,110218.98,0.0,110218.98
7523,ANMARIE RODGERS,GOVERNMENT AND PUBLIC AFFAIRS MANAGER,110218.94,0.0,110218.94
10331,CHRISTINE MAGOFFIN,"ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS ...",91398.95,0.0,95283.35
28870,BEVERLY HENNESSEY,GOVERNMENT AND PUBLIC AFFAIRS MANAGER,21642.9,0.0,23257.32
42332,AnMarie Rodgers,Govrnmt/Publ Affairs Mgr,112394.47,0.0,115880.47
44060,Bart Broome,Govrnmt/Publ Affairs Mgr,104445.7,0.0,107931.70
65421,Sharyn Saslafsky,Govrnmt/Publ Affairs Mgr,4239.19,0.0,27938.05
79417,AnMarie Rodgers,Govrnmt/Publ Affairs Mgr,119757.02,0.0,119757.02
105751,Bart S Broome,Govrnmt/Publ Affairs Mgr,NaN,0.0,10908.62
119805,Aaron D Starr,Govrnmt/Publ Affairs Mgr,106866.42,0.0,106866.42

## 12. Replace 'Not Provided' in EmployeeName Column with Most common value

In [15]:
data['BasePay'] = data['BasePay'].replace("Not Provided",data['BasePay'].mode()[0])
data['BasePay']

0         167411.18
1         155966.02
2         212739.13
3           77916.0
4          134401.6
            ...
148649         0.00
148650          0.0
148651          0.0
148652          0.0
148653         0.00
Name: BasePay, Length: 148654, dtype: object

## 13. Find Minimum , Maximum and Average Basepay

In [16]:
data['BasePay'] = data['BasePay'].astype(float)
data['BasePay'].describe()

count    148049.000000
mean      66323.656854
std       42765.447379
min        -166.010000
25%       33583.520000
50%       65006.930000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

## 14. Drop The Row Having 5 Missing Values

In [17]:
data = data[data.isnull().sum(axis=1) != 5]

In [18]:
data.isnull().sum(axis=1)

0         1
1         1
2         1
3         1
4         1
         ..
148649    0
148650    0
148651    0
148652    0
148653    0
Length: 148654, dtype: int64

## 15. Find Job Title of ALBERT PARDINI

In [19]:

data[data['EmployeeName'] =='ALBERT PARDINI']['JobTitle']

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

## 16. How Much ALBERT PARDINI Make (Including Benefits) ?

In [20]:
data[data['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

## 17. Display Name of The Person Having Highest Basepay

In [21]:
data[data['BasePay'].max() == data['BasePay']][['EmployeeName','BasePay']]

         EmployeeName    BasePay
72925  Gregory P Suhr  319275.01

## 18. Find Average Basepay of All Employee per Year

In [22]:
data['Year'] = pd.to_numeric(data['Year'],errors= 'coerce')

In [23]:
data.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66557.437750
Name: BasePay, dtype: float64

## 19. Find Average BasePay of All Employee Per Job Title

In [24]:
data.groupby('JobTitle')['BasePay'].mean()

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2159, dtype: float64

## 20. Find Average BasePay of All Employee Having Job Title ACCOUNTANT

In [25]:
data[data['JobTitle'] == 'ACCOUNTANT']['BasePay'].mean()

np.float64(46643.172)

## Find Average BasePay of All Employee Having Job Title All  ACCOUNTANT

In [26]:
data[data['JobTitle'].str.contains('ACCOUNTANT')]['BasePay'].mean()

np.float64(63668.260187265914)

## 21. Find Top 5 Most Commons Jobs

In [27]:
data['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

## 22. Find Top 10 High Paying Job Title

In [28]:
data[['JobTitle', 'BasePay']].sort_values(by='BasePay', ascending=False).head(10)

                            JobTitle    BasePay
72925                Chief of Police  319275.01
110532             Asst Med Examiner  318835.49
72929   Dep Dir for Investments, Ret  315572.01
72926         Chief, Fire Department  313686.01
72931    Executive Contract Employee  313312.52
72932                    Dept Head V  311758.96
110537                   Dept Head V  311298.55
110538   Executive Contract Employee  310161.02
110534               Chief of Police  307450.04
72933     Gen Mgr, Public Trnsp Dept  305307.89